[versions]
adapterdelegates4KotlinDsl = "4.3.2"
ksp = "2.0.10-1.0.24"
agp = "8.5.2"
androidxPaletteKtx = "1.0.0"
facebookShimmer = "0.5.0"
gradle = "8.5.2"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinGradlePlugin = "2.0.10"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
media = "1.7.0"
navigationUiKtx = "2.8.2"
retrofit2 = "2.11.0"
glide = "4.16.0"
paging = "3.3.2"
fragmentKtx = "1.8.4"
activityKtx = "1.9.2"
kotlinxCoroutinesCore = "1.7.3"
viewpager2 = "1.1.0"
roomRuntime = "2.6.1"
media3Session = "1.4.1"
media3Exoplayer = "1.4.1"
material3Android = "1.3.0"
jsoup = "1.13.1"
koinAndroid = "4.0.0"

[libraries]
adapterdelegates4-kotlin-dsl = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl", version.ref = "adapterdelegates4KotlinDsl" }
hannesdorfmann-adapterdelegates4-kotlin-dsl-viewbinding = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl-viewbinding", version.ref = "adapterdelegates4KotlinDsl" }
koinAndroid= { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "androidxPaletteKtx" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "facebookShimmer" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
paging = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3Session" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

[plugins]
jetbrainsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }