[versions]
accompanistDrawablepainterVersion = "0.32.0"
accompanistSystemuicontrollerVersion = "0.27.0"
adapterdelegates4KotlinDsl = "4.3.2"
coilCompose = "2.7.0"
constraintlayoutCompose = "1.1.1"
haze = "1.3.1"
ksp = "2.1.10-1.0.30"
agp = "8.5.2"
androidxPaletteKtx = "1.0.0"
facebookShimmer = "0.5.0"
gradle = "8.5.2"
kotlin = "2.1.10"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
kotlinGradlePlugin = "2.0.10"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
media = "1.7.0"
navigationUiKtx = "2.8.8"
retrofit2 = "2.11.0"
glide = "4.16.0"
paging = "3.3.6"
fragmentKtx = "1.8.6"
activityKtx = "1.10.1"
kotlinxCoroutinesCore = "1.10.1"
viewpager2 = "1.1.0"
roomRuntime = "2.6.1"
material3Android = "1.3.1"
jsoup = "1.13.1"
koinAndroid = "4.0.0"
activityCompose = "1.10.1"
materialVersion = "1.7.8"
navigationCompose = "2.8.8"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistDrawablepainterVersion" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "materialVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "materialVersion" }
adapterdelegates4-kotlin-dsl = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl", version.ref = "adapterdelegates4KotlinDsl" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontrollerVersion" }
hannesdorfmann-adapterdelegates4-kotlin-dsl-viewbinding = { module = "com.hannesdorfmann:adapterdelegates4-kotlin-dsl-viewbinding", version.ref = "adapterdelegates4KotlinDsl" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
insert-koin-koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroid" }
koinAndroid= { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "androidxPaletteKtx" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "facebookShimmer" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
paging = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }